### ISSUE TITLE
请教代码问题

### ISSUE THREAD

**Issue by zyx12355** [Cai-Zi/CycleGANProject#3]
您好，我尝试了一下你的代码。有以下问题：
Traceback (most recent call last):
  File "C:/Users/zyx/Desktop/CycleGANProject-master/test.py", line 5, in <module>
    from models import ResnetGenerator
  File "C:\Users\zyx\Desktop\CycleGANProject-master\models\__init__.py", line 2, in <module>
    from .UGATIT_sadalin_hourglass import UgatitSadalinHourglass
  File "C:\Users\zyx\Desktop\CycleGANProject-master\models\UGATIT_sadalin_hourglass.py", line 7, in <module>
    from utils import *
  File "C:\Users\zyx\Desktop\CycleGANProject-master\utils\__init__.py", line 1, in <module>
    from .preprocess import Preprocess
  File "C:\Users\zyx\Desktop\CycleGANProject-master\utils\preprocess.py", line 1, in <module>
    from .face_detect import FaceDetect
  File "C:\Users\zyx\Desktop\CycleGANProject-master\utils\face_detect.py", line 4, in <module>
    import face_alignment
ModuleNotFoundError: No module named 'face_alignment'

请问要如何解决

**Comment by MaoFuyou** [comment]
pip install face_alignment==1.0.0

**Comment by luduangit** [comment]
没有photo2cartoon_10000.pt文件呐
